export enum Parametro {
  SCORE_CREDITICIO = 'SCORE_CREDITICIO',
  SITUACION_BCRA   = 'SITUACION_BCRA',
  MONTO_SOLICITADO = 'MONTO_SOLICITADO',
  PLAZO_SOLICITADO = 'PLAZO_SOLICITADO',
  EDAD             = 'EDAD',
  INGRESOS         = 'INGRESOS',
}
